# This is a basic workflow to help you get started with Actions

name: GitHub Version Management

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # setup msbuild
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      # setup nuget
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
        
      # restore nuget packages
      - name: Pre-Build
        run: .github\\tools\\bash.exe .github\\scripts\\preBuild.sh
        
      # build
      - name: Build
        run: .github\\tools\\bash.exe .github\\scripts\\build.sh
  
      # post build
      - name: Post-Build
        run: .github\\tools\\bash.exe .github\\scripts\\postBuild.sh